from rest_framework import serializers

class FirePredictionSerializer(serializers.Serializer):
    Temperature = serializers.FloatField()
    Wind = serializers.FloatField()
    Precipitation = serializers.FloatField()
    Barometer = serializers.FloatField()
    Partially = serializers.FloatField()
    Month = serializers.IntegerField()
    Hour = serializers.IntegerField()
    DayOfWeek = serializers.IntegerField()
    Season_Summer = serializers.BooleanField()
    Season_Typhoon = serializers.BooleanField()
    Season_Wet = serializers.BooleanField()
    Weather_Heavy_rain = serializers.BooleanField()
    Weather_Light_rain = serializers.BooleanField()
    Weather_Overcast = serializers.BooleanField()
    Weather_Partly_sunny = serializers.BooleanField()
    Weather_Passing_clouds = serializers.BooleanField()
    Weather_Scattered_clouds = serializers.BooleanField()
    Weather_Sprinkles = serializers.BooleanField()
    Weather_Thundershowers = serializers.BooleanField()
    Weather_Thunderstorms = serializers.BooleanField()
    Weather_Thunderstorms_dot = serializers.BooleanField()