# Generated by Django 5.1.1 on 2024-12-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='force_submit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='report_count',
            field=models.IntegerField(default=0),
        ),
    ]
