# Generated by Django 5.1.1 on 2024-10-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='violation',
            field=models.IntegerField(default=0),
        ),
    ]
