# Generated by Django 4.2.16 on 2024-12-02 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_report_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_count',
            field=models.IntegerField(default=0),
        ),
    ]
