# Generated by Django 4.2.16 on 2024-09-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('emergency', 'Emergency'), ('maintenance', 'Maintenance')], max_length=20, null=True),
        ),
    ]
