# Generated by Django 5.1.1 on 2024-10-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_violation'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='custom_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='floor_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phofile_image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
