# Generated by Django 4.2.16 on 2025-01-26 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='department_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
