# Generated by Django 5.1.1 on 2024-10-28 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_report_custom_type_report_floor_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phofile_image_path',
            new_name='profile_image_path',
        ),
    ]
