# Generated by Django 4.2.16 on 2024-10-01 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_is_email_verified_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ipv',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
