# Generated by Django 5.1.1 on 2024-10-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_phofile_image_path_user_profile_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image_path',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
