# Generated by Django 4.2.16 on 2024-10-09 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_ipv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('emergency', 'Emergency'), ('not emergency', 'Not Emergency'), ('maintenance', 'Maintenance')], max_length=20, null=True),
        ),
    ]
