# Generated by Django 5.1.1 on 2024-10-29 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_profile_image_path'),
        ('api', '0006_user_account_status'),
    ]

    operations = [
    ]
