# Generated by Django 4.2.16 on 2024-10-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_report_downvote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='category',
        ),
        migrations.AddField(
            model_name='report',
            name='categories',
            field=models.CharField(choices=[('emergency', 'Emergency'), ('not emergency', 'Not Emergency'), ('maintenance', 'Maintenance')], max_length=20, null=True),
        ),
    ]
