# Generated by Django 5.1.1 on 2024-10-18 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_report_category_report_categories'),
        ('api', '0008_verifyaccount'),
    ]

    operations = [
    ]
