# Generated by Django 5.1 on 2024-11-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('department', models.CharField(max_length=100)),
                ('station', models.CharField(max_length=100)),
                ('station_address', models.CharField(max_length=255)),
                ('home_address', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('worker', 'Worker'), ('department_admin', 'Department Admin'), ('department_head', 'Department Head'), ('superadmin', 'Super Admin')], max_length=50),
        ),
    ]
