# Generated by Django 4.2.16 on 2024-10-22 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_report_category_report_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='categories',
            new_name='is_emergency',
        ),
    ]
