# Generated by Django 5.1.1 on 2024-10-22 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_merge_20241018_1455'),
        ('api', '0009_rename_categories_report_is_emergency'),
    ]

    operations = [
    ]
