# Generated by Django 5.1 on 2024-10-21 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_merge_20241018_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='categories',
            new_name='category',
        ),
    ]
