# Generated by Django 4.2.16 on 2024-11-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_department_delete_worker_user_home_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coordinates',
            field=models.TextField(blank=True, null=True),
        ),
    ]
